spring:
  activemq:
    # 虚拟机测试地址
    broker-url: tcp://192.168.151.131:61616
    user: admin
    password: admin
# 自定义队列
my_queue:  springboot-queue
# 自定义topic
my_topic: springboot-topic
server:
  port: 8080